/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_universe_free: (a: number, b: number) => void;
export const universe_new: () => number;
export const universe_new_empty: (a: number, b: number) => number;
export const universe_new_random: (a: number, b: number) => number;
export const universe_tick: (a: number) => void;
export const universe_clear: (a: number) => void;
export const universe_randomize: (a: number) => void;
export const universe_render: (a: number) => [number, number];
export const universe_width: (a: number) => number;
export const universe_set_width: (a: number, b: number) => void;
export const universe_height: (a: number) => number;
export const universe_set_height: (a: number, b: number) => void;
export const universe_cells: (a: number) => number;
export const universe_set_cell: (a: number, b: number, c: number, d: number) => void;
export const universe_is_cell_alive: (a: number, b: number, c: number) => number;
export const universe_new_with_pattern_wasm: (a: number, b: number, c: any) => number;
export const universe_set_cells_wasm: (a: number, b: any) => void;
export const universe_get_cells_wasm: (a: number) => [number, number];
export const universe_toggle_cell: (a: number, b: number, c: number) => void;
export const universe_draw_blinker: (a: number, b: number, c: number, d: number) => void;
export const universe_draw_glider: (a: number, b: number, c: number) => void;
export const universe_draw_pulsar: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
